---
extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
rules:
  class-methods-use-this: 0
  no-constant-condition: 0
  no-duplicate-imports: 0
  no-else-return: 0
  no-restricted-syntax:
    - 2
    - selector: 'FunctionDeclaration'
      message: 'Unexpected use of function keyword. Prefer arrow functions'
  prettier/prettier: 2
env:
  jest: true
parser: 'babel-eslint'
plugins:
  - flowtype
  - prettier
